# Test zip command on windows-latest runner with shell: bash

name: Test

on:
  push:
    branches: [ main ]

jobs:
  test-zip-command:

    runs-on: windows-latest

    steps:
#       - name: Install "zip"
#         run: |
#           choco install zip
#         shell: bash

      - name: Test command -> zip
        run: |
          zip --help
        shell: bash
