# Test

name: Test

on:
  push:
    branches: [ main ]

jobs:
  test-node-range:

    runs-on: windows-latest

    env:
      NODE_RANGE: node14

    steps:
      - name: check env 1
        run: |
          echo $NODE_RANGE
        shell: bash
      - name: check env 2
        run: |
          echo ${{ env.NODE_RANGE }}
        shell: bash
